name: Chromatic

on:
  push:
    branches:
      - master
      - next*
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - packages/bezier-react/**

jobs:
  chromatic-deployment:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Save PR number and Chromatic build outputs
        run: |
          mkdir -p ./pr
          echo ${{ github.event.pull_request.number }} > ./pr/prNumber
          echo "abc" > ./pr/storybookUrl
          echo "123" > ./pr/buildUrl

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
